# used for development/testing
version: '3'
services:
  service_indexer:
    image: service_indexer
    build:
      context: .
    runtime: nvidia
    network_mode: 'host'
    volumes:
      - ${PROJECT_PATH}:/app
      - ${PROJECT_PATH}/cache:/app/cache
    command: bash -c "fastapi run /app/src/run_indexer.py --port 8001"
    ports:
      - 6333
      - 6334
      - 8001:8001
    environment:
      CUDA_VISIBLE_DEVICES: ${CUDA_VISIBLE_DEVICES:-0}

  service_autocompleter:
    image: service_autocompleter
    build:
      context: .
    runtime: nvidia
    network_mode: 'host'
    volumes:
      - ${PROJECT_PATH}:/app
      - ${PROJECT_PATH}/cache:/app/cache
    command: bash -c "fastapi run /app/src/run_autocompleter.py --port 8002"
    ports:
      - 6333
      - 6334
      - 8001:8001
    environment:
      CUDA_VISIBLE_DEVICES: ${CUDA_VISIBLE_DEVICES:-0}

  service_index_db:
      image: qdrant/qdrant
      network_mode: 'host'
      volumes:
        - ${PROJECT_PATH}/qdrant_storage:/app/qdrant/storage
      ports:
        - 6333:6333
        - 6334:6334
  service_searcher:
    image: service_searcher
    build:
      context: .
    runtime: nvidia
    network_mode: 'host'
    volumes:
      - ${PROJECT_PATH}:/app
      - ${PROJECT_PATH}/cache:/app/cache
    command: bash -c "fastapi run /app/src/main.py --port 8000"
    ports:
      - 6333
      - 6334
      - 8000:8000
    environment:
      CUDA_VISIBLE_DEVICES: ${CUDA_VISIBLE_DEVICES:-0}
